export const GET_COMMENTS_LOAD = "GET_COMMENTS_LOAD";
export const GET_COMMENTS_SUCC = "GET_COMMENTS_SUCC";
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";

export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";

export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

export const TOGGLE_TRUE = "TOOGLE_TRUE";
export const TOGGLE_FALSE = "TOOGLE_FALSE";

export const GET_COMMENT_LOAD = "GET_COMMENT_LOAD";
export const GET_COMMENT_SUCC = "GET_COMMENT_SUCC";
export const GET_COMMENT_FAIL = "GET_COMMENT_FAIL";

export const EDIT_COMMENT_SUCC = "EDIT_COMMENT_SUCC";
export const EDIT_COMMENT_FAIL = "EDIT_COMMENT_FAIL";
