export const GET_TRANSPORTS_LOAD = "GET_TRANSPORTS_LOAD";
export const GET_TRANSPORTS_SUCC = "GET_TRANSPORTS_SUCC";
export const GET_TRANSPORTS_FAIL = "GET_TRANSPORTS_FAIL";

export const DELETE_TRANSPORT_FAIL = "DELETE_TRANSPORT_FAIL";

export const ADD_TRANSPORT_FAIL = "ADD_TRANSPORT_FAIL";

export const TOGGLE_TRUE = "TOOGLE_TRUE";
export const TOGGLE_FALSE = "TOOGLE_FALSE";

export const GET_TRANSPORT_LOAD = "GET_TRANSPORT_LOAD";
export const GET_TRANSPORT_SUCC = "GET_TRANSPORT_SUCC";
export const GET_TRANSPORT_FAIL = "GET_TRANSPORT_FAIL";

export const EDIT_TRANSPORT_SUCC = "EDIT_TRANSPORT_SUCC";
export const EDIT_TRANSPORT_FAIL = "EDIT_TRANSPORT_FAIL";
